apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configmap
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: hzcluster
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: hazelcast-service #Refers to k8s service that expose port 5701 to cluster, null == default
      map:
        default:
          time-to-live-seconds: 240
        main-cache:
          time-to-live-seconds: 180
  